### PR TITLE
Revert "add 50 nodes"

### PR DESCRIPTION
**Pull request by andreer**
Reverts vespa-cloud/vespa-documentation-search#153

### CODE REVIEW

**Comment by andreer** [comment]
Don't merge this just yet ...

**Review by frodelu — APPROVED** [review]

**Comment by frodelu** [comment]
Only approving it so it's ready to merge when you're ready to scale down.

**Comment by andreer** [comment]
Looks like I don't have permission to merge in this repo

**Comment by frodelu** [comment]
You want me to merge, @andreer ?

**Comment by andreer** [comment]
Please do!

**Pull request merged**
